version: "3.8"

services:
  redis:
    image: redis:alpine
    networks:
      - hyperledger
    ports:
      - 6379:6379

  backend:
    build: .
    depends_on:
      - redis
    ports:
      - 8000:8000
    volumes:
      - "${PWD}/network.yaml:/out/network.yaml"
    networks:
      - hyperledger
    environment:
      - REDIS_URL=redis://redis:6379
      
networks:
  hyperledger:
    name: fabric_test
    external: true
