# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

networks:
  test:
    name: fabric_test
    external: true
    
volumes:
  hyperledger:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=${NFS_IP},rw,relatime,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2
      device: ":${NFS_DEVICE}"

services:

  ca_org1:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
      com.docker-tc.enabled: 1
      com.docker-tc.limit: 100mbps
      com.docker-tc.delay: 800ms
      com.docker-tc.loss: 1%
      com.docker-tc.corrupt: 1%
    environment:
      - FABRIC_CA_HOME=/hyperledger/network/organizations/fabric-ca/org1
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
        - type: volume
          source: hyperledger
          target: /hyperledger
    container_name: ca_org1
    networks:
      - test
    deploy:
      placement:
        constraints:
          - node.labels.org == org1

  ca_org2:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
      com.docker-tc.enabled: 1
      com.docker-tc.limit: 100mbps
      com.docker-tc.delay: 800ms
      com.docker-tc.loss: 1%
      com.docker-tc.corrupt: 1%
    environment:
      - FABRIC_CA_HOME=/hyperledger/network/organizations/fabric-ca/org2
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    ports:
      - "8054:8054"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
        - type: volume
          source: hyperledger
          target: /hyperledger
    container_name: ca_org2
    networks:
      - test
    deploy:
      placement:
        constraints:
          - node.labels.org == org2

  ca_org3:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
      com.docker-tc.enabled: 1
      com.docker-tc.limit: 100mbps
      com.docker-tc.delay: 800ms
      com.docker-tc.loss: 1%
      com.docker-tc.corrupt: 1%
    environment:
      - FABRIC_CA_HOME=/hyperledger/network/organizations/fabric-ca/org3
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
        - type: volume
          source: hyperledger
          target: /hyperledger
    container_name: ca_org3
    networks:
      - test
    deploy:
      placement:
        constraints:
          - node.labels.org == org3
      
  ca_orderer:
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
      com.docker-tc.enabled: 1
      com.docker-tc.limit: 100mbps
      com.docker-tc.delay: 800ms
      com.docker-tc.loss: 1%
      com.docker-tc.corrupt: 1%
    environment:
      - FABRIC_CA_HOME=/hyperledger/network/organizations/fabric-ca/ordererOrg
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19054
    ports:
      - "9054:9054"
      - "19054:19054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
        - type: volume
          source: hyperledger
          target: /hyperledger
    container_name: ca_orderer
    networks:
      - test
