version: "3.8"

services:
  populatewallet:
    build: .
    volumes:
      - "${PWD}/wallet:/app/wallet2"
      - "../../network/organizations/peerOrganizations/:/app/peerOrganizations"
    networks:
      - hyperledger
    command: "bash -c 'rm -f /app/wallet2/* && cd /app && /app/generateWallet && cp /app/wallet/* /app/wallet2/ && chmod 644 /app/wallet2/*'"
      
networks:
  hyperledger:
    name: fabric_test
    external: true
