version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - hyperledger
 #   ports:
 #     - 6379:6379

  minio-server:
    image: minio/minio
    restart: unless-stopped
    volumes:
     - minio_storage:/data
    ports:
     - "9000:9000"
     - "9001:9001"
    networks:
      - hyperledger
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address :9001 /data

  minio-client:
    image: minio/mc
    networks:
      - hyperledger
    volumes:
      - "${PWD}/sample_files/:/files/"
    depends_on:
      - minio-server
    entrypoint: >
     /bin/sh -c "sleep 5 &&
     /usr/bin/mc config host add myminio http://minio-server:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
     /usr/bin/mc mb myminio/input-files;
     /usr/bin/mc cp /files/* myminio/input-files
     "

  backend:
    restart: unless-stopped
    build: ./backend
    depends_on:
      - redis
      - minio-server
    volumes:
      - "${PWD}/backend/network.yaml:/out/network.yaml"
    networks:
      - hyperledger
      - web
    environment:
      - REDIS_URL=redis://redis:6379
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_URL=http://minio-server:9000
      
  frontend:
    restart: unless-stopped
    build: ./frontend
    depends_on:
      - backend
    ports:
     - "80:80"
    networks:
      - web
      
networks:
  hyperledger:
    name: fabric_test
    external: true
  web:
    name: web
    
volumes:
  minio_storage:
