version: "3.8"

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - hyperledger
 #   ports:
 #     - 6379:6379

  minio-server:
    image: minio/minio
    restart: unless-stopped
    volumes:
     - minio_storage:/data
    ports:
     - "9000:9000"
     - "9001:9001"
    networks:
      - hyperledger
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    command: server --console-address :9001 /data
    networks:
      hyperledger:
        aliases:
          - minio-server

  minio-client:
    image: minio/mc
    networks:
      - hyperledger
    volumes:
      - "${PWD}/sample_files/:/files/"
    depends_on:
      - minio-server
    entrypoint: >
     /bin/sh -c "sleep 5 &&
     /usr/bin/mc config host add myminio http://minio-server:9000 admin adminadmin;
     /usr/bin/mc mb myminio/input-files;
     /usr/bin/mc cp /files/* myminio/input-files
     "

  backend:
    restart: unless-stopped
    image: registry.gitlab.com/artas182x/dockerimages_blockchaindataprocessor/backend:0.1
    build: ./backend
    depends_on:
      - redis
      - minio-server
    volumes:
      - "${PWD}/network.yaml:/out/network.yaml"
    networks:
      - hyperledger
    environment:
      - REDIS_URL=redis://redis:6379
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
      - MINIO_URL=http://minio-server:9000
    networks:
      hyperledger:
        aliases:
          - backend
      
  frontend:
    restart: unless-stopped
    image: registry.gitlab.com/artas182x/dockerimages_blockchaindataprocessor/frontend:0.1
    build: ./frontend
    depends_on:
      - backend
    ports:
     - "80:80"
    networks:
      - hyperledger
      
networks:
  hyperledger:
    external:
      name: fabric_test
    
volumes:
  minio_storage:
